# Generated by Django 4.0.1 on 2022-02-14 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('plan_type', models.CharField(max_length=20)),
                ('water_volume', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=50)),
                ('water_level', models.IntegerField(default=2000)),
                ('moisture_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watering_status', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TimePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gadget_communicator_pull.basicplan')),
            ],
        ),
        migrations.CreateModel(
            name='WaterTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=20)),
                ('time_water', models.TimeField()),
                ('time_plan_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gadget_communicator_pull.timeplan')),
            ],
        ),
        migrations.CreateModel(
            name='MoisturePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture_threshold', models.IntegerField(default=0)),
                ('check_interval', models.IntegerField(default=0)),
                ('basic_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gadget_communicator_pull.basicplan')),
            ],
        ),
        migrations.AddField(
            model_name='basicplan',
            name='device_relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gadget_communicator_pull.device'),
        ),
    ]
