# Generated by Django 4.2.24 on 2025-09-29 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gadget_communicator_pull', '0002_alter_basicplan_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='status',
            name='gadget_comm_executi_ba7931_idx',
        ),
        migrations.RemoveIndex(
            model_name='status',
            name='gadget_comm_status__a30c89_idx',
        ),
        migrations.RemoveIndex(
            model_name='status',
            name='gadget_comm_device__ea3cd3_idx',
        ),
        migrations.RemoveIndex(
            model_name='status',
            name='gadget_comm_created_cd64d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='status',
            name='gadget_comm_status__5af055_idx',
        ),
        migrations.RemoveField(
            model_name='status',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='status',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='status',
            name='status_type',
        ),
        migrations.RemoveField(
            model_name='status',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='status',
            name='execution_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='message',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_time',
            field=models.CharField(default='', max_length=40),
        ),
    ]
