DEVICE = 'device'
HAS_BEEN_EXECUTED = 'has_been_executed'
DEVICES = 'devices'
WATER_LEVEL = 'water_level'
MOISTURE_LEVEL= 'moisture_level'
EXECUTION_STATUS = 'execution_status'
EXECUTION_MESSAGE = 'message'
IMAGE = 'image'